// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkNEskut1NWgwZzpGnSrJ2xEQpTak3X10',
    appId: '1:714947697386:web:a1c4fea0dfa80c20c8d593',
    messagingSenderId: '714947697386',
    projectId: 'project-900091ab-837c-412a-940',
    authDomain: 'project-900091ab-837c-412a-940.firebaseapp.com',
    storageBucket: 'project-900091ab-837c-412a-940.firebasestorage.app',
    measurementId: 'G-9WQX5HKTSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_oC8uEXi0sS4EWiOLQGQ7kv8Eiu-Fy8U',
    appId: '1:714947697386:android:f64b8c53d95bf293c8d593',
    messagingSenderId: '714947697386',
    projectId: 'project-900091ab-837c-412a-940',
    storageBucket: 'project-900091ab-837c-412a-940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmAwU59FO5RHwbxVafd4ARYR42DbXg6A',
    appId: '1:714947697386:ios:80fbdb4f05d611fcc8d593',
    messagingSenderId: '714947697386',
    projectId: 'project-900091ab-837c-412a-940',
    storageBucket: 'project-900091ab-837c-412a-940.firebasestorage.app',
    androidClientId: '714947697386-tbms98u50vck25r417o1dvgvttno29jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadithApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmAwU59FO5RHwbxVafd4ARYR42DbXg6A',
    appId: '1:714947697386:ios:80fbdb4f05d611fcc8d593',
    messagingSenderId: '714947697386',
    projectId: 'project-900091ab-837c-412a-940',
    storageBucket: 'project-900091ab-837c-412a-940.firebasestorage.app',
    androidClientId: '714947697386-tbms98u50vck25r417o1dvgvttno29jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadithApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkNEskut1NWgwZzpGnSrJ2xEQpTak3X10',
    appId: '1:714947697386:web:7a490c3fc5a7d2d7c8d593',
    messagingSenderId: '714947697386',
    projectId: 'project-900091ab-837c-412a-940',
    authDomain: 'project-900091ab-837c-412a-940.firebaseapp.com',
    storageBucket: 'project-900091ab-837c-412a-940.firebasestorage.app',
    measurementId: 'G-2LSHQ7PZCQ',
  );
}
